spring:
  application:
    name: azureservicebusclient
    cloud:
      config:
        failFast: false
        uri: http://cloudconfig:8888

server:
  port: ${PORT:8001}

feign:
  hystrix:
    enabled: false    
    
azure:
  servicebus:
    connection-string: 
    queue-name: testqueue
    queue-receive-mode: peeklock
    